<html>
    <head>
        <title>Aritmatika</title>
    </head>
    <body>
        <?php
            $numw=5;
            $numq=3;
            echo "Pertambahan ".$numw." + ".$numq." = ".($numw+$numq)."<br/>";
            echo "Pengurangan ".$numw." - ".$numq." = ".($numw-$numq)."<br/>";
            echo "Perkalian ".$numw." x ".$numq." = ".($numw*$numq)."<br/>";
            echo "Pembagian ".$numw." : ".$numq." = ".($numw/$numq);
            /*Multi line
             comen
             */
            //Single Line comen
            #Single Line com
        ?>
    </body>
</html>

